version: "3"

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile_postgres
    container_name: db
    image: db
    restart: on-failure
    environment:
      POSTGRES_USER: ${db_login}
      POSTGRES_PASSWORD: ${db_passwd}
      POSTGRES_DB: books
    ports:
      - "5432:5432"

  server_app:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile_app
    image: server_app
    container_name: server_app
    restart: on-failure
    ports:
      - "9284:9284"
    environment:
      db_login: ${db_login}
      db_passwd: ${db_passwd}
    volumes:
      - ./:/app
    depends_on:
      - db
      - rabbit

  loader_app:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile_loader
    image: loader_app
    container_name: loader_app
    restart: on-failure
    environment:
      db_login: ${db_login}
      db_passwd: ${db_passwd}
    volumes:
      - ./:/app
    depends_on:
      - db
      - rabbit
      - server_app

  rabbit:
    image: rabbitmq:latest
    container_name: rabbit
    restart: on-failure
    ports:
      - "5672:5672"



