FROM python:3.8-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY ./requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT ./wait-for-it.sh loader_app:9284 -- python3 loader.py > stdout.txt