FROM python:3.8-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY ./requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT ./wait-for-it.sh db:5432 -- ./wait-for-it.sh rabbit:5672 -- python3 server.py
